// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD04GRpi_6TXQ6zVSscKIxMMUYoRkRhixQ',
    appId: '1:286160692796:web:339ecd30da833c38d10539',
    messagingSenderId: '286160692796',
    projectId: 'apna-store-5',
    authDomain: 'apna-store-5.firebaseapp.com',
    storageBucket: 'apna-store-5.firebasestorage.app',
    measurementId: 'G-SV7V7YZWWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4CzeZfl8_5lFnD0nQadHLFiCxSqygKI',
    appId: '1:286160692796:android:0641c22d4bb825f0d10539',
    messagingSenderId: '286160692796',
    projectId: 'apna-store-5',
    storageBucket: 'apna-store-5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD04GRpi_6TXQ6zVSscKIxMMUYoRkRhixQ',
    appId: '1:286160692796:web:d1d993f56b516a08d10539',
    messagingSenderId: '286160692796',
    projectId: 'apna-store-5',
    authDomain: 'apna-store-5.firebaseapp.com',
    storageBucket: 'apna-store-5.firebasestorage.app',
    measurementId: 'G-G8L1JGKL6V',
  );
}
